# Generated by Django 2.2.16 on 2020-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, help_text='City is displayed in the bot message', max_length=64)),
                ('state', models.CharField(blank=True, help_text='State is displayed in the bot message', max_length=64)),
                ('zipcode', models.CharField(help_text='Required to lookup the weather data on openweathermap.org API.', max_length=64)),
                ('country_code', models.CharField(help_text='2-digit country code. Required to lookup the weather data on openweathermap.org API.', max_length=32)),
            ],
        ),
    ]
