# Generated by Django 2.2.16 on 2020-12-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0002_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name_plural': 'Weather'},
        ),
    ]
