# Generated by Django 2.2.16 on 2021-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0005_auto_20210501_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('expires', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reminders',
            },
        ),
    ]
